version: '3'

services:
  web:
    build: .
    container_name: myproject
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
    ports:
      - "8000:8000"


  nginx:
    container_name: myproject_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
    depends_on:
      - web
    
volumes:
  static_volume:
  postgres_data:



